# Generated by Django 4.2.3 on 2023-10-16 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Inventory", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="quantity",
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name="purchaseorderitems",
            name="quantity",
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name="purchaseorderitems",
            name="unit_price",
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name="returnproductdetails",
            name="return_quantity",
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name="storerequest",
            name="quantity",
            field=models.BigIntegerField(),
        ),
    ]
