# Generated by Django 4.2.5 on 2023-10-30 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0002_hotel_contact_2_hotel_facebook_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
