# Generated by Django 4.2.3 on 2023-10-16 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Restaurant", "0002_alter_restauranttransaction_bill_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="food",
            name="unit_price",
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="quantity",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="tablereservation",
            name="contact",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="totalcredit",
            name="credit_amount",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="totalcredit",
            name="guestnumber",
            field=models.BigIntegerField(),
        ),
    ]
