# Generated by Django 4.2.3 on 2023-10-29 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Restaurant", "0003_alter_food_unit_price_alter_orderitem_quantity_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="totalcredit",
            name="restaurant_transaction",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Restaurant.restauranttransaction",
            ),
        ),
    ]
