# Generated by Django 4.2.3 on 2023-10-29 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Restaurant", "0004_totalcredit_restaurant_transaction"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="totalcredit",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="totalcredit",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="totalcredit",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
