# Generated by Django 4.2.3 on 2023-10-29 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Guest", "0001_initial"),
        (
            "Restaurant",
            "0005_alter_totalcredit_options_totalcredit_created_at_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="totalcredit",
            options={"ordering": ["-id"]},
        ),
        migrations.AddField(
            model_name="creditdetails",
            name="return_amount",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="totalcredit",
            name="membership",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="Guest.membership",
            ),
        ),
    ]
