# Generated by Django 4.2.3 on 2023-10-29 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Restaurant", "0006_alter_totalcredit_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="totalcredit",
            name="guestnumber",
            field=models.BigIntegerField(null=True),
        ),
    ]
