# Generated by Django 4.2.5 on 2023-10-31 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Authentication', '0003_alter_hotel_website'),
        ('Guest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spa_name', models.CharField(max_length=200)),
                ('spa_contact', models.CharField(max_length=200)),
                ('capacity', models.IntegerField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SpaMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_guest', models.BooleanField(default=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('guest_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.guest')),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.membership')),
            ],
        ),
        migrations.CreateModel(
            name='SpaService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('duration', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SpaPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packagetype', models.CharField(choices=[('massages', 'massages'), ('facials', 'facials'), ('bodywraps', 'bodywraps'), ('steambaths', 'steambaths')], max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('included_service', models.ManyToManyField(related_name='included_in_packages', to='GymandSpa.spaservice')),
                ('spa_membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GymandSpa.spamember')),
                ('spaserviceid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages_offering_this_service', to='GymandSpa.spaservice')),
            ],
        ),
        migrations.AddField(
            model_name='spamember',
            name='spa_package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GymandSpa.spapackage'),
        ),
        migrations.CreateModel(
            name='SpaFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('comment', models.CharField(max_length=200)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('spamember_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GymandSpa.spamember')),
            ],
        ),
        migrations.CreateModel(
            name='SpaBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customername', models.CharField(max_length=200)),
                ('dateandtime', models.DateTimeField(auto_now_add=True)),
                ('duration', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Payment_status', models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid')], default='Unpaid', max_length=200)),
                ('contact_no', models.CharField(max_length=200)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('service_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GymandSpa.spaservice')),
            ],
        ),
        migrations.CreateModel(
            name='NutritionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('dailymealplan', models.CharField(max_length=200)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('gym_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.membership')),
            ],
        ),
        migrations.CreateModel(
            name='GymPackages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration', models.DurationField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('hotel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Authentication.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='GymMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_guest', models.BooleanField(default=False)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Inactive', max_length=200)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('guest_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.guest')),
                ('gym_packages_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GymandSpa.gympackages')),
                ('hotel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Authentication.hotel')),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.membership')),
            ],
        ),
        migrations.CreateModel(
            name='GymFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(auto_now_add=True)),
                ('comment', models.CharField(max_length=200)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('gym_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.membership')),
                ('hotel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Authentication.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='GymAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('gym_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.membership')),
                ('hotel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Authentication.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='Gym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gym_name', models.CharField(max_length=200)),
                ('gym_contact', models.CharField(max_length=200)),
                ('gym_capacity', models.IntegerField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('hotel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Authentication.hotel')),
            ],
        ),
    ]
