# Generated by Django 4.2.5 on 2023-11-03 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0003_alter_hotel_website'),
        ('GymandSpa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpaInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('hotel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Authentication.hotel')),
                ('spa_booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GymandSpa.spabooking')),
                ('spa_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GymandSpa.spamember')),
            ],
        ),
        migrations.CreateModel(
            name='GymInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('gym_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GymandSpa.gymmember')),
                ('gym_packages', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GymandSpa.gympackages')),
                ('hotel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Authentication.hotel')),
            ],
        ),
    ]
