# Generated by Django 4.2.5 on 2023-11-05 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GymandSpa', '0002_spainvoice_gyminvoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gympackages',
            name='duration',
            field=models.CharField(max_length=200),
        ),
    ]
