# Generated by Django 4.2.5 on 2023-11-06 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GymandSpa', '0005_remove_spamember_spa_package'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gymfeedback',
            old_name='Date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='spabooking',
            old_name='Payment_status',
            new_name='payment_status',
        ),
        migrations.RemoveField(
            model_name='gyminvoice',
            name='gym_packages',
        ),
        migrations.RemoveField(
            model_name='spapackage',
            name='included_service',
        ),
        migrations.RemoveField(
            model_name='spapackage',
            name='spa_membership',
        ),
        migrations.RemoveField(
            model_name='spapackage',
            name='spaserviceid',
        ),
        migrations.RemoveField(
            model_name='spaservice',
            name='duration',
        ),
        migrations.AddField(
            model_name='spamember',
            name='spa_package',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='GymandSpa.spapackage'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spamember',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spapackage',
            name='duration',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spaservice',
            name='package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='GymandSpa.spapackage'),
        ),
        migrations.AlterField(
            model_name='nutritionplan',
            name='gym_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GymandSpa.gymmember'),
        ),
    ]
