# Generated by Django 4.2.3 on 2023-11-07 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("GymandSpa", "0008_alter_gymmember_guest_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gymattendance",
            name="gym_member",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="GymandSpa.gymmember"
            ),
        ),
        migrations.AlterField(
            model_name="gymfeedback",
            name="gym_member",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="GymandSpa.gymmember"
            ),
        ),
    ]
